site_url: "https://youcefmegoura.online"
cv_download_url: "https://docs.google.com/document/d/1aTyHQ-nfRT2nSHtT7tuWv_jnZqYUM9tc_p-DYncKD_A/export?format=pdf"
social:
  linkedin: "https://www.linkedin.com/in/youcefmegoura/"
  github: "https://github.com/youcefmegoura"
  email: "ymegoura@gmail.com"
  phone: "+33 7 45 26 74 00"
og_image: "/og-cover.jpg"
